from dotenv import load_dotenv
load_dotenv()

import os

DISCORD_TOKEN_MAID = os.getenv('DISCORD_TOKEN_MAID')
DISCORD_TOKEN_MASTER = os.getenv('DISCORD_TOKEN_MASTER')
DISCORD_TOKEN_ORCHESTRATOR = os.getenv('DISCORD_TOKEN_ORCHESTRATOR')

# LLM (Azure OpenAI) 設定
GPT_41MINI_CHAT_KEY = os.getenv('GPT_41MINI_CHAT_KEY')
GPT_41MINI_CHAT_ENDPOINT = os.getenv('GPT_41MINI_CHAT_ENDPOINT')
GPT_41MINI_CHAT_MODEL = os.getenv('GPT_41MINI_CHAT_MODEL')
GPT_41MINI_CHAT_VERSION = os.getenv('GPT_41MINI_CHAT_VERSION')

#監視感覚
MONITOR_INTERVAL = 0.5

# Langfuse設定
LANGFUSE_SECRET_KEY = os.getenv('LANGFUSE_SECRET_KEY')
LANGFUSE_PUBLIC_KEY = os.getenv('LANGFUSE_PUBLIC_KEY')
LANGFUSE_HOST_URL = os.getenv('LANGFUSE_HOST_URL')